name: Lint and type check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun i

      - name: Lint
        run: bun lint

      - name: Type check
        run: bun tsc

      - name: Prettier check
        run: bunx prettier . --check

      - name: Syncpack check
        run: bunx syncpack lint
