name: Build Tauri

on:
  workflow_dispatch:
    inputs:
      platform-macos:
        type: boolean
        description: Whether to build for macOS
        default: true
      platform-ubuntu:
        type: boolean
        description: Whether to build for Ubuntu
        default: true
      platform-windows:
        type: boolean
        description: Whether to build for Windows
        default: true

jobs:
  build:
    if: ${{ github.event.inputs.platform-macos == 'true' || github.event.inputs.platform-ubuntu == 'true' || github.event.inputs.platform-windows == 'true' }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform:
          - macos-latest
          - ubuntu-22.04
          - windows-latest
        args:
          - "--target aarch64-apple-darwin"
          - "--target x86_64-apple-darwin"
          - ""
        exclude:
          - platform: ${{ github.event.inputs.platform-macos != 'true' && 'macos-latest' }}
          - platform: ${{ github.event.inputs.platform-ubuntu != 'true' && 'ubuntu-22.04' }}
          - platform: ${{ github.event.inputs.platform-windows != 'true' && 'windows-latest' }}
          - platform: macos-latest
            args: ""
          - platform: ubuntu-22.04
            args: "--target aarch64-apple-darwin"
          - platform: ubuntu-22.04
            args: "--target x86_64-apple-darwin"
          - platform: windows-latest
            args: "--target aarch64-apple-darwin"
          - platform: windows-latest
            args: "--target x86_64-apple-darwin"

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Log inputs
        run: |
          echo "${{ toJSON(github.event.inputs) }}"
          echo "${{ toJSON(matrix) }}"

      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Install Ubuntu dependencies
        if: matrix.platform == 'ubuntu-22.04' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install dependencies
        run: bun i

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: apps/tauri
          tagName: app-v__VERSION__
          releaseName: "App v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}
